pipeline {
    agent any
    environment{
        //Dockerhub credentials is set in jenkins settings and is accessed here.
        DOCKERHUB_CREDENTIALS = credentials('shreyas607-dockerhub')
        IMAGE_NAME = 'shreyas607/flaskapp'
        //Build number is generated by jenkins automatically.
        //$BUILD_NUMBER = 1
    }
    stages {
        stage('clone') {
            steps {
                git 'https://github.com/Shreyas-Hardy-33/YOLOv11-FLASK_DOCKER_APP.git'
            }
        }

        stage('Build Docker Image'){
            steps{
                echo "$IMAGE_NAME:$BUILD_NUMBER"
                bat 'docker build -t %IMAGE_NAME%:%BUILD_NUMBER% .'
            }
        }

        stage('Push to Docker Hub'){
            steps{
                script{
                    bat 'echo %DOCKERHUB_CREDENTIALS_PSW% | docker login -u %DOCKER_CREDENTIALS_USR%'
                    bat 'docker push %IMAGE_NAME:%BUILD_NUMBER%'
                    
                }
            }
        }

        //This is for testing the app in my system before deployment
        stage('Deploy to Stage'){
            steps{
                bat 'docker run -d -p 5000:5000  %IMAGE_NAME:%BUILD_NUMBER%'
            }
        }
        
    }
}
