pipeline {
    agent any
    environment{
        //Dockerhub credentials is set in jenkins settings and is accessed here.
        DOCKERHUB_CREDENTIALS = credentials('shreyas607-dockerhub')
        IMAGE_NAME = 'shreyas607/flaskapp'
        //Build number is generated by jenkins automatically.
        //$BUILD_NUMBER = 1
    }
    stages {
        stage('clone') {
            steps {
                git 'https://github.com/Shreyas-Hardy-33/YOLOv11-FLASK_DOCKER_APP.git'
            }
        }

        stage('Build Docker Image'){
            steps{
                echo "$IMAGE_NAME:$BUILD_NUMBER"
                bat 'docker build -t $IMAGE_NAME:$BUILD_NUMBER .'
            }
        }
        
    }
}
