pipeline{
    agent any
    environment{
        //Dockerhub credentials is set in jenkins settings and is accessed here.
        DOCKERHUB_CREDENTIALS = credentials('shreyas607-dockerhub')
        IMAGE_NAME = 'shreyas607/flaskapp'
        //Build number is generated by jenkins automatically.
        $BUILD_NUMBER = 1
    }

    stages{
        stage('Git repository download'){
            steps{
                git 'https://github.com/Shreyas-Hardy-33/YOLOv11-FLASK_DOCKER_APP.git'
            }
        }

        stage('Install dependencies'){
            steps{
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Build Docker Image'){
            steps{
                sh 'docker build -t $IMAGE_NAME:$BUILD_NUMBER .'
            }
        }

        stage('Push to DockerHub'){
            steps{
                script{
                    sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKER_CREDENTIALS_USR --password-stdin'
                    sh 'docker push $IMAGE_NAME:$BUILD_NUMBER'
                }
            }
        }

        stage('Deploy to Stage'){
            steps{
                sh 'docker run -d -p 5000:5000 $IMAGE_NAME:$BUILD_NUMBER'
            }
        }

    }


}
